# Generated by Django 5.0.6 on 2024-06-22 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='uploadExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('excel_file', models.FileField(upload_to='uploaded_excels/')),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
